### PR TITLE
fix(test): fixes is-clean test leftover folder

### LINKED ISSUE #17: [BUG] npm run test leaves a test/is-clean folder behind, on Windows, after running
# What / Why

`npm run test` leaves a test/is-clean folder behind, on Windows, after running

## When

* n/a

## Where

* n/a

## How
* n/a

### Current Behavior

Git cloning the repository on Windows and running `npm run test` leaves a test/is-clean folder behind even when the test is successful.

### Steps to Reproduce

On a Windows machine execute the following commands:

```
mkdir tests
cd tests
git clone git@github.com:npm/git.git git
cd git
npm install
npm run test
```

### Expected Behavior

`npm run test` should leave no temporary folder after a successful run

### PR DESCRIPTION
**Pull request by ferdinando-ferreira**
On Windows, this test was leaving a test/is-clean leftover folder after concluding the tests, caused by process.chdir preventing windows from deleting the temporary folder by virtue of being in use.

## References

Closes #17

### CODE REVIEW

File: test/is-clean.js [hunk 1]
```diff
@@ -2,32 +2,34 @@ const isClean = require('../lib/is-clean.js')
...
   write('hello', 'goodbye')
-  .then(() => t.resolveMatch(isClean({cwd}), false)))
+  .then(() => t.resolveMatch(isClean({cwd: repo}), false)))
 
-t.test('default to cwd', t => {
-  process.chdir(cwd)
+t.test('default to repo', t => {
+  const cwd = process.cwd()
+  t.teardown(() => process.chdir(cwd))
+  process.chdir(repo)
```
Comment (ferdinando-ferreira) [inline test/is-clean.js:33]: This is the actual change made to this test, mirroring what was already done on https://github.com/npm/git/blob/master/test/spawn.js. 

Changing `cwd` to `repo` across the test was meant to harmonize both files nomenclatures, with `cwd` being the actual (then former, then actual again) `process.cwd` folder and repo being the newly created testdir.
